//  -*- mode: groovy-mode

pipeline {
    agent any 

    stages {
        stage('Checkout') {
            steps { 
                node('master') {
                    milestone(1)

                    script {
                        retry(3) {
                            try {
                                checkout scm
                            }
                            catch (err) {
                                echo "GITHUB checkout failed, retrying in 5min"
                                sleep 300
                            }
                        }
                    }

                    script {
                        try {
                            echo "Trying enterprise branch ${env.BRANCH_NAME}"

                            checkout(
                                changelog: false,
                                poll: false,
                                scm: [
                                    $class: 'GitSCM',
                                    branches: [[name: "*/${env.BRANCH_NAME}"]],
                                    doGenerateSubmoduleConfigurations: false,
                                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'enterprise']],
                                    submoduleCfg: [],
                                    userRemoteConfigs: [[credentialsId: '8d893d23-6714-4f35-a239-c847c798e080', url: 'https://github.com/arangodb/enterprise']]])
                        }
                        catch (err) {
                            echo "Failed ${env.BRANCH_NAME}, trying enterprise branch devel"

                            checkout(
                                changelog: false,
                                poll: false,
                                scm: [
                                    $class: 'GitSCM',
                                    branches: [[name: "*/devel"]],
                                    doGenerateSubmoduleConfigurations: false,
                                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'enterprise']],
                                    submoduleCfg: [],
                                    userRemoteConfigs: [[credentialsId: '8d893d23-6714-4f35-a239-c847c798e080', url: 'https://github.com/arangodb/enterprise']]])
                        }
                    }

                    sh 'rm -rf build build-jenkins'

                    stash includes: '**', name: 'source'
                }
            }
        }

        stage('Build CC LX') { 
            steps { 
                node('linux') {
                    milestone(2)

                    unstash 'source'

                    sh './Installation/Pipeline/build_cc_lx.sh 16'

                    stash includes: 'build/**,etc/**,Installation/Pipeline/**,js/**,scripts/**,tests/**,UnitTests/**', name: 'build-cc-lx'
                }
            }
        }

        stage('Basic Tests') {
            steps {
                parallel(
                    'jsunity': {
                        node('linux || mac') {
                            unstash 'build-cc-lx'

                            script {
                                try {
                                    sh './Installation/Pipeline/jslint.sh'
                                }
                                catch (exc) {
                                    currentBuild.result = 'UNSTABLE'
                                }
                            }
                        }
                    },

                    'test-ss-mm-cc-lx': {
                        node('linux') {
                            unstash 'build-cc-lx'

                            lock('test_ss_mm_cc_lx') {
                                sh './Installation/Pipeline/test_ss_mm_cc_lx.sh 8'
                            }
                        }
                    },

                    'test-cl-rd-cc-lx': {
                        node('linux') {
                            unstash 'build-cc-lx'

                            lock('test_cl_rd_cc_lx') {
                                sh './Installation/Pipeline/test_cl_rd_cc_lx.sh 8'
                            }
                        }
                    }

                )
            }
        }

        stage('Build EE') { 
            steps { 
                parallel(
                    'build-ee-ma': {
                        node('mac') {
                            unstash 'source'

                            sh './Installation/Pipeline/build_ee_mc.sh 16'

                            stash includes: 'build/**,etc/**,Installation/Pipeline/**,js/**,scripts/**,tests/**,UnitTests/**', name: 'build-ee-mc'
                        }
                    },

                    'build-ee-wi': {
                        node('windows') {
                            unstash 'source'

                            bat './Installation/Pipeline/build_ee_wi.bat'

                            stash includes: 'build/**,etc/**,Installation/Pipeline/**,js/**,scripts/**,tests/**,UnitTests/**', name: 'build-ee-wi'
                        }
                    }
                )
            }
        }
    }
}
